# Generated by Django 5.0.1 on 2024-01-29 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="companyDataTable",
            fields=[
                (
                    "comid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("companyname", models.CharField(max_length=100)),
                ("comregno", models.CharField(max_length=500)),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.CharField(max_length=200)),
                ("tel", models.CharField(max_length=50)),
                ("preffield", models.CharField(max_length=300)),
                ("linkedin", models.CharField(blank=True, max_length=1000, null=True)),
                ("createtimestamp", models.DateTimeField(auto_now_add=True)),
                ("updatetimestamp", models.DateTimeField(auto_now_add=True)),
                ("profilepic", models.ImageField(blank=True, null=True, upload_to="")),
                ("username", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="studentDataTable",
            fields=[
                (
                    "stuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.CharField(max_length=200)),
                ("tel", models.CharField(max_length=50)),
                ("university", models.CharField(max_length=200)),
                ("degree", models.TextField(blank=True, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=1000, null=True)),
                ("createtimestamp", models.DateTimeField(auto_now_add=True)),
                ("updatetimestamp", models.DateTimeField(auto_now_add=True)),
                ("profilepic", models.ImageField(blank=True, null=True, upload_to="")),
                ("username", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StudentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stuid", models.CharField(default=None, max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("summary", models.TextField()),
                ("description", models.TextField()),
                ("lect_comment", models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="ComNotification",
            fields=[
                (
                    "ComNotificationId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("notification", models.TextField(blank=True, null=True)),
                (
                    "createtimestamp",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("MarkAsRead", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.companydatatable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="flyerdata",
            fields=[
                (
                    "flyerid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("jobfield", models.CharField(max_length=100)),
                ("jobpost", models.CharField(max_length=100)),
                ("salary", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=1000)),
                ("flyerimage", models.ImageField(upload_to="")),
                ("createtimestamp", models.CharField(max_length=30)),
                ("updatetimestamp", models.CharField(max_length=30)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.companydatatable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="studentapply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.flyerdata",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.studentdatatable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="message",
            fields=[
                (
                    "msgid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("msg", models.TextField(blank=True, null=True)),
                ("sender", models.CharField(max_length=200)),
                ("senderID", models.CharField(blank=True, max_length=200, null=True)),
                ("Receiver", models.CharField(max_length=200)),
                ("ReceiverID", models.CharField(blank=True, max_length=200, null=True)),
                ("MarkAsRead", models.CharField(blank=True, max_length=5, null=True)),
                ("createtimestamp", models.CharField(max_length=30)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.companydatatable",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.studentdatatable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="studentfavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.flyerdata",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.studentdatatable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StuNotification",
            fields=[
                (
                    "StuNotificationId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("notification", models.TextField(blank=True, null=True)),
                (
                    "createtimestamp",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("MarkAsRead", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkplaceApp.studentdatatable",
                    ),
                ),
            ],
        ),
    ]
