# Generated by Django 5.0.1 on 2024-01-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WorkplaceApp", "0002_stdntlog_delete_studentlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stdntlog",
            name="lect_comment",
            field=models.TextField(default=None, null=True),
        ),
    ]
