# Generated by Django 5.0.1 on 2024-01-29 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WorkplaceApp", "0003_alter_stdntlog_lect_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="lecturerDataTable",
            fields=[
                (
                    "lecid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.CharField(max_length=200)),
                ("tel", models.CharField(max_length=50)),
                ("createtimestamp", models.DateTimeField(auto_now_add=True)),
                ("updatetimestamp", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, to="WorkplaceApp.studentdatatable"
                    ),
                ),
            ],
        ),
    ]
