# Generated by Django 5.0.1 on 2024-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WorkplaceApp", "0004_lecturerdatatable"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerdatatable",
            name="profilepic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="lecturerdatatable",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
