# Generated by Django 5.0.1 on 2024-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WorkplaceApp", "0005_lecturerdatatable_profilepic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturerdatatable",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="lecturers", to="WorkplaceApp.studentdatatable"
            ),
        ),
    ]
